// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RideForgeApi.Persistence;

#nullable disable

namespace RideForgeApi.Persistence.Migrations
{
    [DbContext(typeof(RideForgeDbContext))]
    partial class RideForgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rideforge")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RideForgeApi.Persistence.SavedRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientRouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_route_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("distance_meters");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<double>("RequestedDistanceKm")
                        .HasColumnType("double precision")
                        .HasColumnName("requested_distance_km");

                    b.Property<string>("StartLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("start_label");

                    b.Property<double>("StartLat")
                        .HasColumnType("double precision")
                        .HasColumnName("start_lat");

                    b.Property<double>("StartLng")
                        .HasColumnType("double precision")
                        .HasColumnName("start_lng");

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Geometry", "RideForgeApi.Persistence.SavedRoute.Geometry#Coord", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Lat")
                                .HasJsonPropertyName("lat");

                            b1.Property<double>("Lng")
                                .HasJsonPropertyName("lng");

                            b1
                                .ToJson("geometry")
                                .HasColumnType("jsonb");
                        });

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "ClientRouteId")
                        .IsUnique()
                        .HasDatabaseName("ux_saved_routes_owner_client_route");

                    b.ToTable("saved_routes", "rideforge");
                });
#pragma warning restore 612, 618
        }
    }
}
